# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      
      - name: Get repo version
        id: repo-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Get latest package version
        id: latest-package-version
        run: echo "version=$(npm view @s809/noisecord version)" >> "$GITHUB_OUTPUT"
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - run: npm publish
        if: steps.repo-version.outputs.current-version != steps.latest-package-version.outputs.version
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
